### ISSUE TITLE
Support for SMILES 

### ISSUE THREAD

**Issue by gustalima** [3dmol/3Dmol.js#456] opened 2020-05-19 09:14 UTC
I would like to be able to parse smiles to display small molecules, something like 

 <script src="http://3Dmol.csb.pitt.edu/build/3Dmol-min.js"></script> </head>    
         <div style="height: 400px; width: 400px; position: relative;" class='viewer_3Dmoljs' data-smiles='COC1CC(Cl)NC(SC)N1' data-backgroundcolor='0xffffff' data-style='stick'></div>       

Maybe it is already possible, but I could not find a way to do it.

Best, 
Gustavo

**Comment by dkoes** [comment] 2020-05-19 13:11
SMILES are a 2D format.  You need to convert to something with coordinates before you can look at it in 3Dmol.js.

**Comment by dkoes** [comment] 2020-05-19 13:11
Duplicate of #287

**Closed by dkoes** 2020-05-19 13:11 UTC
Labels: enhancement
