### ISSUE TITLE
[BUG] After 1.6.1 upgrade, "inFront" option no longer works on labels (v1.6.0 breaks it)

### ISSUE THREAD

**Issue by andfaulkner** [3dmol/3Dmol.js#484] opened 2020-11-23 22:09 UTC
**Description**
Labels no longer appear in front of atoms when the "inFront" config option is set.

**To Reproduce**
Attach a label to an atom, and view:
`
viewer.addLabel(atomIndex, {fontSize: 11.5, inFront: true}, {serial: atom.serial});
`

Note: code simplified for purpose of example.

**Expected behavior**
The labels should appear in front of the atoms, like they used to.

**Screenshots**
Before upgrade:
![Screen Shot 2020-11-23 at 5 01 26 PM](https://user-images.githubusercontent.com/7527436/100020724-4891b480-2dae-11eb-916c-1ae79c635aa9.png)

After upgrade:
![Screen Shot 2020-11-23 at 5 05 11 PM](https://user-images.githubusercontent.com/7527436/100020708-416aa680-2dae-11eb-9171-498b7a8bac79.png)

Note that the colour differences on the labels don't reflect the issue - I confirmed that the config options are still getting applied, I just changed the colour settings to make it clearer where the labels are being rendered post-change.

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.13.5
 - Browser: Chrome
 - Version: 87.0.4280.67

**Comment by dkoes** [comment] 2020-11-24 01:01
I cannot reproduce this.  Can you provide a reduced test case?  Does the following have labels in front for you?
https://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=testlabelfront

**Comment by andfaulkner** [comment] 2020-11-24 06:21
@dkoes It does. Before creating a test case, is it possible the issue is coming from this change? https://github.com/3dmol/3Dmol.js/issues/482

I built 3dmol locally to get access to the feature early (it was a blocker on my end), so it could be that that's where the issue was introduced.

**Comment by dkoes** [comment] 2020-11-24 13:00
I don't see how.  Does the test case above work for you?

Have you downgraded to an older version of 3dmol without changing your code to verify the issue isn't with your code?

**Comment by andfaulkner** [comment] 2020-11-25 03:01
Agreed...I looked at your code changes and also didn't see how, which is why I attributed it to v1.6.1.

I did try downgrading to v1.5.4 and the issue disappeared. However, I loaded the earlier versions in through the CDN, rather than building locally, so it's possible that's a factor. My code itself didn't change - it only affected the build/load process...but I've been using 3dmol for about 2 years now, and every other time I've had issue related to that, it's just stopped working altogether.

Based on all this, I'm going to try the following and get back to you:
- [ ] Testing directly with v1.6.1 loaded in with my standard method (the CDN)
- [ ] To rule out build process weirdness, I'll manually build and include v1.6.1 the way I did with the bleeding-edge version: build from your code (with gulp), then store the dist locally and pull it into my application with Webpack.
- [ ] 100% ensure the gulp version and plugins I built with precisely matched your versions
- [ ] Pull in your test case and trying it with my own local 3dmol setup

(Also, sorry for the latency...my daughter was up all teething last night and it's delayed everything today)

**Comment by andfaulkner** [comment] 2020-11-25 06:21
**It turns out the issue was introduced with v1.6.0**.

It still happens when v1.6.1 is loaded into the app by CDN:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/3Dmol/1.6.1/3Dmol-nojquery.js"></script>`

I retested v1.5.4 to double-check, and it's still working there; then tried v1.6.0, and it broke. This is all with no code changes in between (either in the codebase itself, or the build).

**Comment by andfaulkner** [comment] 2020-11-25 07:44
Found the culprit - it's caused by this commit: https://github.com/3dmol/3Dmol.js/commit/2e3152e5659c631b0544520be14064308e78aeed

When the commit is reversed (done manually in the output file), the issue disappears. Re-including it (by reversing the edited output file).

**Comment by dkoes** [comment] 2020-11-25 19:55
Are you setting the opacity of your molecules?

**Comment by dkoes** [comment] 2020-11-26 02:47
I think you must have set the opacity to something not 1.0 on your atoms as that is the only way I can reproduce the problem.  I have pushed a fix.  Does it work now?

**Comment by andfaulkner** [comment] 2020-11-28 06:02
Will give this a try in a couple of days, I'm stuck afk for a bit

**Comment by andfaulkner** [comment] 2020-12-03 08:27
@dkoes Yep, this 100% fixes it. Thanks so much!

**Closed** 2020-12-03 14:35 UTC
Labels: bug
