### ISSUE TITLE
[BUG] Translate movements are uneven and leave viewer off center

### ISSUE THREAD

**Issue by emmori** [3dmol/3Dmol.js#460] opened 2020-07-28 09:02 UTC
**Describe the bug**
When using the viewer translate function the movement is not uniform each time which leads to the viewer getting off center. It seems to be worse the larger the movement.

**To Reproduce**
1. Go to https://3dmol.csb.pitt.edu/tests/example.html

2. Use the following commands in the console:
glviewer.translate(-500, 0);
glviewer.translate(500, 0);

3. Model is no longer centered and can't be reset as the movement is independent from the view matrix.

**Expected behavior**
Moving the viewer one direction "x" amount and moving it back the same amount should put you in the original position.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  84.0.4147.89

**Additional context**
Is there any alternative way to move the model using the view matrix? I know you can use the getView() method and adjust the values, but unsure how I'd do that if I want to move relative to the view (a.k.a ignoring the object rotations).

**Comment by dkoes** [comment] 2020-07-28 21:13
I can't reproduce this.  I've tried using Chrome on both Ubuntu and MacOS (I don't have easy access to a Windows machine). Applying the two translates puts the model exactly back where it started, which is the expected behavior. I'd appreciate help figuring out what is going on here.  Can you reproduce in other browsers/operating systems?

The first three values of the view vector are the x,y,z coordinates of the model center (in model coordinates).  Changing those will translate the model relative to the view.  Note that by model here I mean all displayed structures.  The only way to move individual GLModel's relative to one another is manually change their coordinates.

I think what you want is to be able to translate the molecule just like dragging the mouse.  Interestingly, this functionality wasn't implemented, so I went ahead and added "translateScene" which takes x,y offsets in screen coordinates and can be used to move the models without changing the center of rotation.
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=glviewer_js_translateScene

Let me know if this is what you want.

**Comment by emmori** [comment] 2020-07-29 10:15
You're right. I'm trying to essentially simulate the mouse move options, but with buttons for keyboard accessibility. Currently I'm using the `glviewer.rotate(number, "x/y/z")` for rotations and `glviewer.translate(x,y)` for moving up/down/left/right.

This combo works really well since that translate function doesn't change the model's rotation point. So even if you translate the model to the top left and rotate, it will rotate in place as opposed to using the center of the view as the rotation point. For example:

1. Go to https://3dmol.csb.pitt.edu/tests/example.html

2. Use the following commands in the console:
```
glviewer.translate(-500, 0);
glviewer.rotate(45, "x");
glviewer.rotate(45, "y");
```

In that example even after moving the model it rotates in place.

The translateScene method would be useful as it is exactly what the mouse is doing and would definitely work well in my scenario. Although getting the translate function to work would be ideal as it's easier to use / understand for keyboard only users.

I'm able to reproduce the translate problem on a MacBook Air in both chrome and safari.

OS: Catalina 10.15.3
Chrome: 84.0.4147.105
Safari: 13.0.5

I've added screenshots to show what I'm getting. I used bigger values to make it more obvious:
```
glviewer.translate(-1500, 0);
glviewer.translate(1500, 0);
```
![beforeMove](https://user-images.githubusercontent.com/20299053/88785696-6c8b1380-d189-11ea-95b9-80f6f3785ed7.JPG)
![AfterMove](https://user-images.githubusercontent.com/20299053/88785692-6bf27d00-d189-11ea-8572-f28acf3af4b7.JPG)

**Comment by dkoes** [comment] 2020-07-29 13:28
Okay, with the larger amount of translate I see the dislocation.  This is because of the perspective view of the camera.

translate moves the camera.  translateScene moves the model.  What you are seeing is the expected and desired behavior of translate.  If you switch to ttranslateScene all your issues should be resolved.

**Comment by emmori** [comment] 2020-07-29 14:42
Fair enough, I'll use translateScene. Thanks for the help and great library, do you have a rough idea when a version with translateScene will be published?

**Comment by dkoes** [comment] 2020-07-29 14:51
I'd already pushed to github and updated 3dmol.csb.pitt.edu, but I've also now pushed a release (1.5.4) with the change.  

Closing.

**Closed by dkoes** 2020-07-29 14:51 UTC
Labels: bug
