### ISSUE TITLE
hoverable not working with cartoon style

### ISSUE THREAD

**Issue by jksr** [3dmol/3Dmol.js#379] opened 2018-08-13 03:55 UTC
the callback of sethoverable seems not working with the cartoon style. The other styles are fine.
I'm using this version <script src="http://3Dmol.csb.pitt.edu/build/3Dmol-min.js"></script>

`
window.$3Dmol.download("pdb:" + this.props.searchid, viewer, {}, function () {

    viewer.setStyle({},{cartoon:{}});
    viewer.setHoverable({}, true,
        function (atom, viewer, event, container) {
            console.log('hover', atom);
            if (!atom.label) {
                atom.label = viewer.addLabel(atom.resn + ":" + atom.atom, { position: atom, backgroundColor: 'mintcream', fontColor: 'black' });
            }
        },
        function (atom) {
            console.log('unhover', atom);
            if (atom.label) {
                viewer.removeLabel(atom.label);
                delete atom.label;
            }
        }
    );
    //viewer.setHoverDuration(500);
    console.log('lalala')
    viewer.render();
});
`

**Comment by dkoes** [comment] 2018-08-14 01:55
Hmm, yes, this is because there isn't actually a geometric object displayed that directly corresponds to an atom with cartoon style.  What would your desired behavior be?  For it to work as if there were invisible atom spheres that responded to the hover event?

**Comment by jksr** [comment] 2018-08-14 03:05
Hi David,
Thank you for the quick response. 
Actually I was thinking of something like the behavior of LiteMol, which is when hover event happens in cartoon representation, the cartoon segment of the hovered residue is highlighted.

**Comment by dkoes** [comment] 2018-08-14 12:08
Is the highlighted segment associated with any atoms/residues?  Cartoon segments are typically associated with the alpha carbon and highlighting is left to the implementation of the user.

**Comment by publcif** [comment] 2018-08-14 12:37
I'm sure this used to work in earlier versions 
(see e.g. http://publcif.iucr.org/cifmoldb/webgl/eds.php?pdbid=2por)

However, looking at version 1.3.4, it appears that you may have to work round this by adding the hover callbacks to the atoms, e.g.

   var atoms=viewer.getModel().selectedAtoms();
    for (var a in atoms)
    { 
        atoms[a].hoverable=true;
        atoms[a].hover_callback=function(){
            console.log(this);
        };
        atoms[a].unhover_callback=function(){
            console.log(this);
        };
    }

**Comment by publcif** [comment] 2018-08-14 16:34
Turns out that its not necessarily a version issue - if I also define a click callback:

viewer.setClickable({},true,function(atom,viewer,event,container){});

then the hover callback works for cartoon style ;-)

See http://publcif.co.uk/3Dmol/ for bare-bones example (using version 1.3.4)

**Comment by dkoes** [comment] 2018-08-15 00:42
Yes, you're right.  This was a regression.  I've pushed a fix.
e1da42b96e7f01e428772be94e243b83408d9344

**Closed by dkoes** 2018-08-15 00:42 UTC
